### ISSUE TITLE
p1683 - References for Standard Library Vocabulary Types - an optional case study

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#21]
Sigh.

**Comment by Morwenn** [comment]
I'm curious now :D

**Comment by ThePhD** [comment]
... I'm done. This will show up in the next mailing. And hopefully I will never, ever have to talk about this travesty for the rest of my life.

https://thephd.github.io/vendor/future_cxx/papers/published/p1683r0.html
