### ISSUE TITLE
n3031 - Restartable Functions for Efficient Character Conversions

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#24]
There are a lot of functions that should be proposed for the C Committee's Unicode support. Specifically, we need:

- mbs[r]toc[8,16,32]s, 6 functions
- c[8,16,32]s[r]tombs, 6 functions
- wcs[r]toc[8,16,32]s, 6 functions
- c[8,16,32]s[r]towcs, 6 functions

This is too much to propose at first, and does not include the "single code unit" conversion functions for `wchar_t`. (Notably, because those are fundamentally broken on Windows and IBM machines).

**Comment by ThePhD** [comment]
The minimum we should propose is the first and second bullets. We should leave off everything else, and see if WG14 is interested. Asking for literally everything is a recipe for destroying the whole proposal in front of WG14.

**Comment by Morwenn** [comment]
Have you looked at N2282? http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2282.htm

I'm not sure what happened to this paper, but I could try to find meeting minutes.

**Comment by ThePhD** [comment]
I did know about it, and I met the author here. We coordinated. :D

**Comment by ThePhD** [comment]
N2440

**Comment by ThePhD** [comment]
https://thephd.github.io/vendor/future_cxx/papers/source/C%20-%20Efficient%20Character%20Conversions.html

**Comment by ThePhD** [comment]
N2440 - https://thephd.github.io/vendor/future_cxx/papers/source/C%20-%20Efficient%20Character%20Conversions.html

**Comment by ThePhD** [comment]
[N2500](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2500.pdf) - [Latest](https://thephd.github.io/vendor/future_cxx/papers/source/n2500.html)

**Comment by ThePhD** [comment]
This entire paper is going to be reworked. The current facilities are insufficient due to their intrinsic problems and limitations. See this talk for details on how shitty it is:

https://www.youtube.com/watch?v=X-FLGsa8LVc

**Comment by ThePhD** [comment]
Posted: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2595.pdf

Latest: https://thephd.github.io/vendor/future_cxx/papers/C%20-%20Efficient%20Character%20Conversions.html

**Comment by ThePhD** [comment]
We finally have a form and wording that's ACTUALLY good.

Also, we got approved to do a UTF version of the paper too, so the identical wording is applied there too:

https://thephd.github.io/_vendor/future_cxx/papers/C%20-%20Efficient%20UTF%20Character%20Conversions.html

https://thephd.github.io/_vendor/future_cxx/papers/C%20-%20Efficient%20Character%20Conversions.html

**Comment by h-vetinari** [comment]
Is [N2730](https://thephd.dev/_vendor/future_cxx/papers/C%20-%20Efficient%20Character%20Conversions.html) still in the cards for C23?

**Comment by ThePhD** [comment]
I need to publish by October 15th. Same with any other papers that need to make forward progress.

**Comment by h-vetinari** [comment]
I thought that as a proposal that was already seen, it would still have time [until](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2759.pdf) the end of the year? I mean, from a process perspective, earlier is always better, just trying to not put you under even more pressure than you put yourself under already 🙃

**Comment by ThePhD** [comment]
Until March, basically, is my understanding.

**Comment by h-vetinari** [comment]
N2595 (resp. N2730) should probably get a mention as "Continuing proposals" in the agenda [document](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2866.htm)...?

> > @h-vetinari: I thought that as a proposal that was already seen, it would still have time until the end of the year?
>
> @ThePhD: Until March, basically, is my understanding.
> (March 2021.)

I'm not sure I understand (as that's in the past; unless you mean 2022), but the [schedule](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2864.pdf) doesn't seem to allow anything but editorial changes after the Winter meeting, which has a paper deadline until 2021-12-31? That is, assuming that the paper needs to be voted in as usual.

**Comment by ThePhD** [comment]
We might schedule an extra meeting, but the point is to see all new material by the 2021-12-31 deadline. Given how much interest has been focused on C23, we might need to process papers better. We used to process papers really fast in face-to-face meetings but with the lack of those now thanks to COVID and us denying the Portland 2022 meeting, we've got to make do with remote meetings for now.

My understanding is that anything can be done up until:

> 2022-02-28 Editor revises draft 7 2022-03-07

So by February 28th. That's the last time I can edit the draft. I understand it says editorial but with the volume of changes to make I expect to be merging, fixing, etc. features until basically the last minute. Of course, if the C Committee controls that as a whole ultimately: if they stop working on papers and approving/disapproving things, then the work stops. I will merge every paper that goes through.

**Comment by ThePhD** [comment]
(Also, March 2021 is definitely a typo. It was March 2022.)

**Comment by h-vetinari** [comment]
> We might schedule an extra meeting, but the point is to see all new material by the 2021-12-31 deadline.

Maybe we have a different interpretation of "new", but the schedule says quite explicitly:
> Deadline for initial proposal of new features: 2021-10-15

I'm guessing this doesn't apply to N2595/N2730 because it had already been seen. To be honest I'm not nearly as deep in the process as you are, but just from reading the timeline, it sounds like "all papers still wanting to get into C23 need to be submitted by 2021-12-31", followed by one last meeting that votes in proposals (or not).

I get that the actual editing will take longer and has different deadlines, and if there's another meeting due to the volume, great! That's now a different topic though from my question above: whether N2730 still in the cards for C23 (I brought up the current schedule because - being past the "new features" deadline AFAIU, it would have to appear under "continuing proposals" to still have a chance procedurally)

**Comment by ThePhD** [comment]
N2730 is still on the agenda and still in the running. Success would be greatly increased if I released cuneicode and also put it into another stdlib before that time expires.

**Comment by ThePhD** [comment]
Hey, just want to confirm that:

- This paper is still on the agenda
- I am still working on it (and rolling a public implementation, see: https://github.com/soasis/cuneicode)
- The "final document deadline" has been pushed back towards February 2022 because there was an influx of papers we couldn't quite see just yet

**Comment by h-vetinari** [comment]
Yes I saw, congrats on the first public appearance of cuneicode! 🥳 

> The "final document deadline" has been pushed back towards February 2022 because there was an influx of papers we couldn't quite see just yet

Does that mean that there'll be an extra meeting too? Before Strasbourg? Or the whole C23 schedule is pushed back by 3-6 months?

**Comment by ThePhD** [comment]
Maybe an extra meeting, but also we might push the schedule.

https://twitter.com/__phantomderp/status/1462329618313224201

**Comment by h-vetinari** [comment]
> All tests passed (1206695680 assertions in 2 test cases)

1.2 billion tests sounds like a casual weekend, I reckon. 🙃 

(seriously, mad props for aaaaaaaall of this)

**Comment by ThePhD** [comment]
N2902.

**Comment by h-vetinari** [comment]
The paper is not unfortunately still not mentioned in the February [agenda](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2915.htm)... Maybe this needs to be brought to someone's attention so it can still be scheduled/considered? (I'm aware of how silly it is to ask the C Editor that, but better safe than sorry...)

**Comment by ThePhD** [comment]
Shrug, guess I should e-mail the convener, though I think it's too late to change the schedule now. ¯\\\_(ツ)\_/¯

I'll try to see if I can't add it, and if not then at least get it thrown in the "overflow" bin.

**Comment by h-vetinari** [comment]
There have been schedule corrections in the past, so 🤞

**Comment by ThePhD** [comment]
Further inspection reveals that all the papers listed in the WG14 document log are their old versions. For example, Modern Bit Utilities is r0 when there's an r1, the typeof paper is the older revision, etc. etc.

This is all likely due to the fact that I was slow on the draw. Papers have to be published a month in advance, to give adequate time for the reading period. I missed it, so only old stuff is on the agenda.

I'll still advocate for the new versions, but it might mean this stuff gets pushed back to later.

**Comment by h-vetinari** [comment]
(Please tell me to stop if this is annoying you) Just noticed that the updated [agenda](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2928.htm) for the second half of the Jan/Feb meeting already refers to several new papers (most recent one being N2924 from end of Jan), but still does not mention this paper.

**Comment by h-vetinari** [comment]
I say this i.a. because I'm kinda-sorta expecting another agenda update, seeing that some scheduled papers in the tail end of the February half (including `typeof()` 🥳) have already been accepted.

**Comment by ThePhD** [comment]
It's simply not scheduled for this meeting. There may be time at a later meeting given what we've voted to do with our upcoming meeting schedule. There's also no time to change the agenda now because people need 2 weeks prior notice to read a paper.

**Comment by ThePhD** [comment]
@h-vetinari This is more or less the final form. Let me know if you have any questions or comments. It's the last chance to make it for C23, I think, so it's gotta be as good as I can make it. This paper - and your wishes - are my priority here:

https://thephd.dev/_vendor/future_cxx/papers/C%20-%20Restartable%20and%20Non-Restartable%20Character%20Functions%20for%20Efficient%20Conversions.html

**Comment by h-vetinari** [comment]
> I think, so it's gotta be as good as I can make it.

I think it's excellent, thank you so much for your work on this! Unfortunately (or fortunately?) I don't have much more design feedback to give, but 🤞🤞🤞🤞🤞🤞🤞 that this still makes C23!

The one thing from looking at it again is that I think that section 4.1 could use a more explicit conclusion subsubsection to explain which form was chosen. As in: remove "Therefore, we keep the double-pointer form to retain the information properly." in 4.1.1 and add 4.1.4 à la:

> ### 4.1.4 Proposed choice
> 
> Given the above considerations about consistency with other functionality (no struct returns), the downsides of function forms (2)-(4), and the benchmark indications that the impact of doubly-indirected pointers is negligible in bulk, we therefore propose the double-pointer form, in order to retain the requisite information properly.

Also, the addition of the `restrict` keyword to all the pointers could be mentioned in the changelog (and its use perhaps explained in a short paragraph...?).

**Comment by ThePhD** [comment]
I posted it late because I'm tired and forgot the deadline, despite requesting the paper numbers in-time on the 4th of this month. I can only hope I'm allowed to carry it forward, because otherwise every single paper I've written won't be allowed. No unicode functions, no enum improvements, etc.

**Comment by h-vetinari** [comment]
> I can only hope I'm allowed to carry it forward

[🥳](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3027.htm)

**Comment by h-vetinari** [comment]
Infinite [sadness](https://twitter.com/__phantomderp/status/1549438480526327808). I have no idea what happened (and will hence refrain from colourful adjectives), but it _does_ sound a lot like "oh, there's someone who spent years working out a solution to a decades-old problem that affects everyone - that's interesting, next." If that's even remotely close, then you truly didn't deserve that.

**Comment by ThePhD** [comment]
If it's rejected procedurally, we fail. If it isn't rejected procedurally but the wording sucks, we also fail.

There's effectively a lot of room for failure, and this is me we're talking about here.

**Comment by h-vetinari** [comment]
I was gonna say:

![image](https://user-images.githubusercontent.com/33685575/179823359-77f0101d-c49e-4daf-a6c3-6b0414da177b.png)


> There's effectively a lot of room for failure, and this is me we're talking about here.

But you're right. With you at the helm, this doesn't look impossible. 🤞 🙃 

(Also, not sure how good the minutes will be to give guidance on the re-wording demands, but happy to help if I can)

**Comment by ThePhD** [comment]
If you would like to make critiques of the edits, now would be a good time to (important changes are highlighed specially, as shown in the changelog):

https://thephd.dev/_vendor/future_cxx/papers/C%20-%20Restartable%20and%20Non-Restartable%20Character%20Functions%20for%20Efficient%20Conversions.html

**Comment by h-vetinari** [comment]
Just checking back in - there were still two outstanding changes and two open (AFAICT) points from https://github.com/ThePhD/future_cxx/commit/8575bad3ad28478056f9fbb530fca84d5d41332a, and contrary to the enum papers, this isn't visible as [published](https://www.open-std.org/jtc1/sc22/wg14/www/wg14_document_log.htm) yet.

**Comment by ThePhD** [comment]
I think I addressed those in the next commit, no? And they're not published because I sent it to another person (who made the original request for changes) to see if they wouldn't mind checking it over for feedback.

**Comment by ThePhD** [comment]
Oh my god, the commit got lost in all my attempting to rig the submodule up correctly, AAAA!

**Comment by h-vetinari** [comment]
> Oh my god, the commit got lost in all my attempting to rig the submodule up correctly, AAAA!

It's not the end of the world. Fixing the grammar can be done in an editorial fix I guess?

Also, since n3031 isn't published to the WG14 document log yet, I guess there's still a small window that a correction might arrive in time.

**Comment by h-vetinari** [comment]
> > Oh my god, the commit got lost in all my attempting to rig the submodule up correctly, AAAA!
> 
> It's not the end of the world.

Ah, even better - I had misread that you had already sent it for publication. So coming up with those changes again should definitely be in the realm of possibility. ;-)

**Comment by ThePhD** [comment]
Pushed again. Look it over if you like!

**Comment by h-vetinari** [comment]
Last (🤞) round of comments in one place:
* double "the the" [1](https://github.com/ThePhD/future_cxx/commit/c421ed40ae8ef195af7e6e2f8a4797e201907592#r79073549), [2](https://github.com/ThePhD/future_cxx/commit/c421ed40ae8ef195af7e6e2f8a4797e201907592#r79073549)
* possibly [missing](https://github.com/ThePhD/future_cxx/commit/c421ed40ae8ef195af7e6e2f8a4797e201907592#r79074165) footnote
* possible [clarification](https://github.com/ThePhD/future_cxx/commit/8575bad3ad28478056f9fbb530fca84d5d41332a#r79073767) in the change log
* "embodied in" [nit](https://github.com/ThePhD/future_cxx/commit/8575bad3ad28478056f9fbb530fca84d5d41332a#r79073895)

**Comment by h-vetinari** [comment]
💚 for the kind words and 🙏 for all your work on this. Now all that's left is

![source-3207660788](https://user-images.githubusercontent.com/33685575/180251282-1cc51583-83a1-4dea-b050-432f32e90ee0.gif)

**Comment by h-vetinari** [comment]
> I was still given the ability for a Homework Paper, so I need to re-do the bad wording bits and change it to be better. But, if the changes are too significant to process, it could still be rejected under procedural grounds.

BTW, will this still be decided during the July meeting?

**Comment by ThePhD** [comment]
We will find out tomorrow.

**Comment by h-vetinari** [comment]
> > [...] but it _does_ sound a lot like "oh, there's someone who spent years working out a solution to a decades-old problem that affects everyone - that's interesting, next."
>
> Easy, there. There were just a lot of wording suggestions made and doing them now might constitute too many changes to make it into C23, delaying it for the next revision.

My point is still that - in the interest of the C standard and its relevance in today's world[^1] - this needs to get into C23. The overall work for this paper is 99.9+% done (and it seems people don't disagree about that), so any small wording updates tweaks should come in during the review period or editorially, but not delay this for another X years.

[^1]: not least through all the stuff it underlies (almost all of computing), and the humans developing on top of - much less using - that being subjected to constant suffering for lack of these facilities. That this didn't go in 10-20 years ago is a huge process failure, and you are a giant for having found a way to fix it, prove it & shepherd it this far despite all the existing constraints.

**Comment by ThePhD** [comment]
Procedure and the ability of people in the Committee to read/process homework papers is the limiting factor. If they can't understand it before it's voted in, and it is objected to procedural grounds, we can't get anywhere no matter how sensible/reasonable the desired outcome is.

This is what happens when organizations are under bureaucracy and have bureaucratically-established deadlines inflexible to the needs of the work being done. It's not something I can control without bucking The Process™, but I can't do that because I'm not in charge nor is this a one-person project deal. 🤷‍♀️

**Comment by h-vetinari** [comment]
> Procedure and the ability of people in the Committee to read/process homework papers is the limiting factor

I presume it has been distributed (or at least sent to publication) already, so I'll just shut up and hope for the best.

Thanks again!

**Comment by h-vetinari** [comment]
> We will find out tomorrow.

And? Does this [poll](https://mobile.twitter.com/__phantomderp/status/1550497889679450116?cxt=HHwWiICxtbTnvIQrAAAA) (& r10) mean it died for C23?

**Comment by ThePhD** [comment]
Unless you can give me a Speech 100 character stat in the next 5 minutes, I'm pretty sure it's dead.

**Comment by h-vetinari** [comment]
What's the change request?

**Comment by h-vetinari** [comment]
Or what's the speech? To keep it for C23?

**Comment by ThePhD** [comment]
Yes

**Comment by ThePhD** [comment]
Speech happening now. Wish me luck.

**Comment by h-vetinari** [comment]
Dear colleagues,

As we may sometimes forget in detailed technical discussions, the capabilities that end up in the C standard - and more importantly the lack thereof - ends up influencing an overwhelming portion of modern computing, as almost all modern languages are in some way built on top of C, and suffer its defects.

Text processing is a particularly pernicious problem - in stark contrast to 40 years ago, computing and programming has become truly global, and most languages other than English are harrowingly underserved by the current facilities available in C, which ends up in very real pain for both developers and users the world over.

The facilities in n3031 are the bare minimum we can provide to the world to at least have a reliable way to convert between encodings without spectacular - and non-portable - heroics.

It seems we are all agreed that their design is sound, there is an implementation which has proven itself, and any remaining wording issues can surely be worked out during the review phase or editorially.

But I implore you not to let another X years go by in which we don't provide these facilities to users, over comparatively trivial wording changes.

In particular with the 9 month extension requested from ISO, we will have ample time to fix any remaining details.

Thank you

**Comment by h-vetinari** [comment]
Damn, I was writing this on a phone, sorry I was too slow

**Comment by ThePhD** [comment]
Vote now....

**Comment by ThePhD** [comment]
The vote failed. Not enough consensus to continue.

I'm sorry.

**Comment by h-vetinari** [comment]
> Not enough consensus to continue.

For C23 or at all?!

**Comment by h-vetinari** [comment]
Yegahds

**Comment by h-vetinari** [comment]
I'm sorry too.

**Comment by h-vetinari** [comment]
Seriously tough, you should be _extremely_ proud of yourself, so if you [aren't](https://thephd.dev/finally-embed-in-c23), I'll do it for you: You got 10+ papers into the C standard in the span of ~3 years (many of them solving fundamental problems), which is insane in itself, but you did it while also taking over the editor role and working on some gnarly C++ features, implementing ztd::text & cuneicode, and making it through a pandemic. Despite the bitter pill of unicode failing to make it, this is a monumental achievement! ❤️

**Comment by ThePhD** [comment]
I can see the words you're writing. I can hear them in my head, even. Understand them. Process them.

It just doesn't mean anything to my brain. I'm sorry; it's not your fault.

I'm just broken.

--

Delayed until C???.

**Comment by h-vetinari** [comment]
I'm really sorry you had to go through that. Time to disengage a bit me thinks. I hope you write about it _**when the time is ripe**_ - you have a very readable style and it seems like it may even bring some small amount of catharsis (as sharing a struggle almost always helps with processing it).
