### ISSUE TITLE
N2828 - Unicode Sequences More Than 21 Bits are a Constraint Violation

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#40]
New paper. No number yet. https://thephd.dev/_vendor/future_cxx/papers/C%20-%20Unicode%20Sequences%20More%20Than%2021%20Bits%20are%20a%20Constraint%20Violation.html

**Comment by rurban** [comment]
Note that I proposed a similar restriction in n2932 for C26. https://github.com/rurban/libu8ident/blob/master/doc/n2932.md

**Comment by ThePhD** [comment]
This proposal has already been accepted for C23, I just haven't marked it in this repository.

So that's one less thing your proposal has to do for C2Y/C3X.

**Comment by rurban** [comment]
Ah good to know. So I have to cite it properly. TR39 restricts to max 4 sequences, yours is better.

**Comment by h-vetinari** [comment]
> This proposal has already been accepted for C23, I just haven't marked it in this repository.

Out of curiosity, is there a place other than your blogpost updates (and the eventual update to the working draft) where it's publicly visible which papers have been approved/rejected for C23?

**Comment by ThePhD** [comment]
There will be a list in the latest working draft that lists all accepted papers, like in the ones before it. That's supposed to be the definitive list, since the GitLab Issue Tracker is sort of hidden right now and I haven't finished the website I've been working on for over a year now x.x.

**Comment by ThePhD** [comment]
Added to C23. https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2912.pdf
