### ISSUE TITLE
N3030 - Enhanced Enumerations

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#43]
Enumerations in C suck. We're taking over Clive Pygott's paper to fix that.

**Comment by ThePhD** [comment]
Beat this one into shape with a lot of effort. Not sure it'll make it but at least it's in the best possible shape I can get it.

https://thephd.dev/_vendor/future_cxx/papers/C%20-%20Enhanced%20Enumerations.html

**Comment by h-vetinari** [comment]
Looks like revision 5 ate revision 6 (in the changelog), r5 is still listed as a "previous revision"...

**Comment by ThePhD** [comment]
Yeah, not sure what happened, but thankfully as harmless change.

**Comment by ThePhD** [comment]
Added to C23.
