### ISSUE TITLE
N3029 - Improved Normal Enumerations

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#44]
The status quo for enumerations is actually completely batshit bonkers, and I have no idea how anyone got any work done with exclusively standard C.

What a nightmare.

**Comment by ThePhD** [comment]
Submitted. Here's to hoping we can make enums less doomsday. https://thephd.dev/_vendor/future_cxx/papers/C%20-%20Improved%20Normal%20Enumerations.html

**Comment by h-vetinari** [comment]
Something went wrong in the July [schedule](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3027.htm):
> 5.10 Meneide, Enhancements to Enumerations, r5 [[N 2996](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2996.htm)]
5.11 Meneide, Improved Normal Enumerations, r6 [[N 3021](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n3021.htm)]

should be:

5.10 Meneide, Enhancements to Enumerations, r6 [[N 3021](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n3021.htm)]
5.11 Meneide, Improved Normal Enumerations, r2 [[N 2997](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2997.htm)]

**Comment by ThePhD** [comment]
I sent in the wrong revision count for Improved Normal Enumerations and for Enhancements to Enumerations, which is my bad. Should be okay in the corrected agenda now, though.

**Comment by ThePhD** [comment]
Added to C23.
