### ISSUE TITLE
D1629 - unicode_scalar_value: a type for C++ that represents.

### ISSUE THREAD

**Issue by DJm00n** [ThePhD/future_cxx#50]
Seems some wording is missing here:

https://github.com/ThePhD/future_cxx/blob/15b71d96190a29f01c44fbcb3d92877e059fc917/papers/d1629.html#L2467

**Comment by ThePhD** [comment]
Ooh, thanks for catching this. I'll make sure to update the paper.

**Comment by ThePhD** [comment]
This was updated and fixed.
