### ISSUE TITLE
Editorial issue: terms "empty initialization" and "default initialization" in C23 working draft

### ISSUE THREAD

**Issue by frederick-vs-ja** [ThePhD/future_cxx#59]
The formal definition of term _default initialization_ is introduced by [N3042](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3042.htm). But its meaning is largely different from that of [default-initialization in C++](https://eel.is/c++draft/dcl.init#general-7) (AFAIK it's essentially consistent with value-initialization or zero-initialization in C++). On the other hand, the term _empty initialization_ is introduced by [N2900](https://open-std.org/JTC1/SC22/WG14/www/docs/n2900.htm) but unused.

I think it would be confusing if one find that "default initialization" in C is generally not "default-initialization" in C++. Can we just use "empty initialization" (or alternatively, "zero initialization") for description of such initialization?

Perhaps this repo is not a good place for submitting editorial issue, but I failed to find how to submit editorial issue for C.

**Comment by ThePhD** [comment]
Editorial issues for C can be sent by e-mailing the project editors on this page:

https://www.open-std.org/jtc1/sc22/wg14/www/contacts.html

(I am one of them.)

It is my intention, for C23, to rewrite how the initialization rules are spelled out and introduce better terminology. It might take some time, though; I have to be careful I change no behavior.

**Comment by ThePhD** [comment]
This is done.
