### ISSUE TITLE
Editorial Issue: Some pages in the Annex have a footer with a wrong paragraph reference

### ISSUE THREAD

**Issue by winspool** [ThePhD/future_cxx#60]
On Annex Pages without a Section, the  paragraph reference in the footer is not updates and remain the same as used on the previous page.

Examples from n3054 draft:
Page 503, Annex C: Paragraph reference is §B.31 (see page 502)

Page 506 to 508, Annex E: Paragraph reference is §D.8 (see page  505)
Page 582, Annex I: Paragraph referenceis §H.13 (see page 581)

**Comment by winspool** [comment]
All examples are still present in n3088.pdf
(Page numbers changed)

-- 
Regards ... Detlef

**Comment by ThePhD** [comment]
This is being tracked in National Body comments.
