### ISSUE TITLE
c23_draft (n3054): SHRT_WIDTH is missing in Annex E, statement #3

### ISSUE THREAD

**Issue by winspool** [ThePhD/future_cxx#61]
In Annex E, sentence #3, there is no SHRT_WIDHT listed.
This is wrong, as SHRT_WIDTH is used in the comments
of SHRT_MAX and SHRT_MIN in the same section. (Page 506).

SHRT_WIDTH is also mentioned in § 5.2.4.2.1 in the text
below USHRT_WIDTH (Page 21)

SHRT_WIDTH is also listed in §B.9 (Page 478)

Implementation example from clang:
https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/limits.h#L74

-- 
Regards ...
Detlef

**Comment by winspool** [comment]
Still not fixed in n3088.pdf (Page: 501)

-- 
Regards ... Detlef

**Comment by ThePhD** [comment]
This is done.
