### ISSUE TITLE
File size and page index

### ISSUE THREAD

**Issue by winspool** [ThePhD/future_cxx#63]
The c23 draft n3088.pdf has no page index
and is more than twice as large (6.6MB)
as the previous draft n3047.pdf (3.2MB)
or the current draft n3096.pdf (3.2MB).

Whatever program was used to create n3088.pdf,
please fix the conversion settings or avoid the program
for creating any pdf documents in the future.

-- 
Regards ... Detlef

**Comment by ThePhD** [comment]
This should be fixed now. Thanks for letting us know,

**Comment by winspool** [comment]
Thanks for looking at my report.
I can't read the current draft (password protected),
but the filesize suggests, that the pdf document creation 
was again done with the better programm / program settings.
