### ISSUE TITLE
Ambiguity of `typeof(int())` and its friends in C++

### ISSUE THREAD

**Issue by frederick-vs-ja** [ThePhD/future_cxx#64]
The token sequence `int()` in C++ can be either an _expression_ or a _type-id_, for which `typeof` will give `int` or `int()` respectively.

Perhaps we should specify that when an operand of `typeof` or `typeof_unqual` can be both parsed as an _expression_ and a _type-id_, it is treated as a _type-id_ (for C compatibility).

**Comment by ThePhD** [comment]
`sizeof` has the same issue. Whatever `sizeof` does, `typeof` will do as well, and I'm certain I don't have to write that out in the proposal since it should already be covered from other wording about how to resolve such ambiguities.

**Comment by frederick-vs-ja** [comment]
Oh I see, there's already [[dcl.ambig.res]/2](https://eel.is/c++draft/dcl.ambig.res#2). It might be better to add some new examples there.
