### ISSUE TITLE
c23: Reference to Annex M has a broken Name (6.7.12 Number 5)

### ISSUE THREAD

**Issue by winspool** [ThePhD/future_cxx#70]
The n3096 Draft has in the Attribute section (6.7.12, Number 5) 
a reference with the Name (Annex M.1) to the Table in Annex M with the Name:
Table Annex M.1

In the latest document, the Name of the reference is broken: (??)
The reference links to the same Table in Annex M, but the Table has a different Name:
Table M.1

Is it possible to fix this for the C23 release?

Regards
Detlef

**Comment by ThePhD** [comment]
This is already fixed in the latest, thanks for bringing it up.
