### ISSUE TITLE
p1301 - [[nodiscard("should have a reason")]] for Pre-Kona C++20

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/future_cxx#8]
This was discussed on a [reflector mailing list post](http://lists.isocpp.org/lib/2018/12/9492.php). But the discussion was not "is this useful", it was "we want this now and here are all the crazy things we can do with it in the standard like demanding implementers put this specific text in it!!!".

We also had people specifically saying they want it, but that mandating the actual text is a step too far. I take that as violent agreement that this is a good thing.

Onward, for C++20.

**Comment by slurps-mad-rips** [comment]
This is good to hear! :D

**Comment by ThePhD** [comment]
Submitted.

**Comment by ThePhD** [comment]
This made it in for C++20 and is awaiting wording review by Core.
